import { Inter } from "next/font/google";
import "./globals.css";
import Header from '../components/header'
import localFont from 'next/font/local'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Rakesh Panugoth | Portfolio",
  description: "Generated by create next app",
};
const gilBold = localFont({src:[{path: "../fonts/Gilroy-Bold.ttf"}], variable: '--font-gilBold'})
const gilSemiBold = localFont({src:[{path: "../fonts/Gilroy-SemiBold.ttf"}], variable: '--font-gilSemiBold'})
const gilMedium = localFont({src:[{path: "../fonts/Gilroy-Medium.ttf"}], variable: '--font-gilSemiBold'})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${gilBold.variable} ${gilSemiBold.variable} ${gilMedium.variable}`}>
        <Header/>
        {children}
        </body>
    </html>
  );
}
